//maps/ahl_monorail.bsp
maps/ahl_monorail.ini
maps/ahl_monorail.loc
maps/ahl_monorail.res
maps/ahl_monorail.mat
maps/ahl_monorail.txt
maps/ahl_monorail.wlf
maps/ahl_monorail.awf
gfx/env/tsccity_up.tga
gfx/env/tsccity_dn.tga
gfx/env/tsccity_lf.tga
gfx/env/tsccity_rt.tga
gfx/env/tsccity_ft.tga
gfx/env/tsccity_bk.tga
sound/bulletbait/trainhorn.wav
sound/bulletbait/godrail-1-l.wav
sound/bulletbait/godrail-2-l.wav
sound/bulletbait/godrail
