endlrainhc.wad
maps/ahl_endlrainhc.loc
maps/ahl_endlrainhc.mat
maps/ahl_endlrainhc.txt
maps/ahl_endlrainhc.ini
overviews/ahl_endlrainhc.mom
overviews/ahl_endlrainhc.txt
gfx/env/futurebk.tga
gfx/env/futuredn.tga
gfx/env/futureft.tga
gfx/env/futurelf.tga
gfx/env/futurert.tga
gfx/env/futurebk.tga
sound/hondo/endlrain/rain.wav
sound/hondo/endlrain/rain_inside.wav
sound/hondo/endlrain/rain_window.wav
sound/hondo/endlrain/squeezeit.wav
sound/hondo/endlrain/xgmtp.wav
sprites/rain2.spr