//maps/ahl_temple.bsp
maps/ahl_temple.res
maps/ahl_temple.txt
maps/ahl_temple.ini
maps/ahl_temple.loc
maps/ahl_temple.mat
//sound/jinx/borg_serenity.wav
//sound/jinx/exo_rope1.wav
//sound/jinx/exo_shock.wav
//sound/jinx/jxfireblaze.wav
//sound/jinx/mr_cutbody.wav
//sound/jinx/mr_flowater.wav
//sound/jinx/mr_seawind.wav
//sound/jinx/mr_tclosed.wav
//sound/jinx/mr_tclosing.wav
//sound/jinx/borg_lava1.wav
//sound/jinx/od_dam_wind.wav
//sound/jinx/exo_birds.wav
//sprites/jinx/fountain1b.spr
//sprites/jinx/jx0firesmall.spr
//sprites/jinx/jxcinder.spr
//sprites/jinx/m_blflare4.spr
//sprites/jinx/templefog.spr
models/jxblueglass.mdl
models/jinx/dk_tree4.mdl
models/jinx/dk_readme.txt
gfx/env/phost3up.tga
gfx/env/phost3rt.tga
gfx/env/phost3lf.tga
gfx/env/phost3ft.tga
gfx/env/phost3dn.tga
gfx/env/phost3bk.tga
maps/ahl_temple.awf
