gfx/env/jxstormbk.tga
gfx/env/jxstormdn.tga
gfx/env/jxstormft.tga
gfx/env/jxstormlf.tga
gfx/env/jxstormrt.tga
gfx/env/jxstormup.tga
maps/ahl_stormvale.bsp
maps/ahl_stormvale.ini
maps/ahl_stormvale.loc
maps/ahl_stormvale.mat
maps/ahl_stormvale.txt
maps/ahl_stormvale.res
sound/jinx/borg_crickets.wav
sound/jinx/borg_rain.wav
sound/jinx/borg_wolf.wav
sound/jinx/mr_flowater.wav
sound/jinx/mr_puddle.wav
sound/jinx/mr_thunder1.wav
sound/jinx/mr_windhowl.wav
sprites/jinx/kismetrain.spr