gfx/env/cliffbk.tga
gfx/env/cliffdn.tga
gfx/env/cliffft.tga
gfx/env/clifflf.tga
gfx/env/cliffrt.tga
gfx/env/cliffup.tga
halflife.wad
sound/ambience/bee1.wav
sound/ambience/biotone.wav
sound/ambience/drips.wav
sound/ambience/hawk1.wav
sound/ambience/rocket_groan4.wav
sound/ambience/squitch.wav
sound/ambience/steamburst1.wav
sound/ambience/waterfall3.wav
sound/ambience/wind1.wav
sound/ambience/wind2.wav
sound/ambience/wren1.wav
sprites/flare1.spr
maps/ahlg_actionrail_dc.awf
maps/ahlg_actionrail_dc.ini
maps/ahlg_actionrail_dc.loc
maps/ahlg_actionrail_dc.res
maps/ahlg_actionrail_dc.txt
