gfx/env/starsup.tga
gfx/env/starsdn.tga
gfx/env/starslf.tga
gfx/env/starsrt.tga
gfx/env/starsft.tga
gfx/env/starsbk.tga
sprites/muzzleflash2.spr
sound/ambience/tankidle1.wav
sound/ambience/biggun3.wav
sprites/glow03.spr
sound/ambience/crickets.wav
sound/ambience/drips.wav
sound/ambience/biotone.wav
maps/ahlg_onslaught2_dc.txt
maps/ahlg_onslaught2_dc.loc
maps/ahlg_onslaught2_dc.res
maps/ahlg_onslaught2_dc.ini
maps/ahlg_onslaught2_dc.awf
